
services:
  # 1. REDIS (The Queue)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379" # Optional: For debugging Redis from your laptop
    restart: always

  # 2. WORKER (The Execution Engine)
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    restart: always
    # CRITICAL: This gives the container control over Docker
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - DOCKER_HOST=unix:///var/run/docker.sock

      # - REDIS_PORT=6379
      - REDIS_PASSWORD=myStrongPassword123

    ports:
      - "3023:3023" #Expose API to host
    depends_on:
      - redis

  # 3. Backend (The API)
  backend_api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: Backend
    restart: always
    ports:
      - "3022:3022" #Expose API to host
    volumes:
    - ./backend:/usr/src/app
    - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      # - REDIS_PORT=6379
      - REDIS_PASSWORD=myStrongPassword123
    depends_on:
      - redis